---
- name: gather os facts
  ansible.builtin.gather_facts:
    gather_subset:
      - min

- import_tasks: _yum.yml
  when: ansible_facts.pkg_mgr == 'yum'

- import_tasks: _apt.yml
  when: ansible_facts.pkg_mgr == 'apt'
