---
- name: wait node ready
  vars:
    host_address: "{{hostvars[item].ansible_host}}"
  shell: kubectl get node -o jsonpath='{.items[?(@.status.addresses[0].address == "{{host_address}}")].status.conditions[-1].status}'
  # nodeのstatusは、"Ready"と記録されている.typeではない
  register: node_state
  until: node_state.stdout == "True"
  retries: 60
  delay: 10
  #changed_when: false
  loop: "{{ wait_target_nodes }}"
  # become: false
  # delegate_to: "{{ groups.master[0] }}"
  # run_once: true
