---
- name: install additional packages
  yum:
    name: "{{ additional_packages }}"
    state: latest

- name: enable additional services
  systemd:
    state: started
    enabled: yes
    name: "{{ item }}"
  with_items:
  - "{{ additional_services }}"
