---
- name: import docker role
  # import_role:
  #   name: install_container_runtime
  #   tasks_from: docker
  import_tasks: docker.yml
  when: use_cri == 'docker'

- name: import containerd role
  import_tasks: containerd.yml
  when: use_cri == 'containerd'
