---
- name: confiture sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: no
    reload: no
    sysctl_file: /etc/sysctl.d/k8s.conf
  loop: "{{ require_kernel_param }}"

- name: ensure sysctl configure
  shell: sysctl --system
