---
- name: load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

  # modprobe br_netfilter は、sysctlで設定変更する「前」に行う。
  # とドキュメントに書いてあった
  # > Make sure that the br_netfilter module is loaded before this step.
  #
  # この処理が無いと /proc/sys/net/bridge 以下が存在せず、
  # ↓の処理が失敗するため。
  # (sysctl --systemだと問題無かった)

- name: confiture sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: false
    reload: true
    sysctl_file: /etc/sysctl.d/k8s.conf
  loop: "{{ require_kernel_param }}"
