---
- name: started firewalld
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: firewalld

- name: allow required ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ required_ports + (cni_required_ports | default([]))}}"
  when: enable_firewalld is defined and enable_firewalld|bool

- name: tunl0@NONE set to trusted zone
  firewalld:
    zone: trusted
    interface: tunl0@NONE
    permanent: yes
    immediate: yes
    state: enabled
  when: enable_firewalld is defined and enable_firewalld|bool

# todo: firewalld設定、これだと足りていない(ノード跨いだpod間通信が出来ていない)

- name: deploy Calico
  become: false
  shell: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
  delegate_to: "{{ item }}"
  run_once: true
  loop:
  - "{{ groups.master[0] }}"
