---
- name: allow required ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop: "{{ cni_required_ports }}"
  when: enable_firewalld is defined and enable_firewalld|bool

- name: started firewalld
  systemd:
    state: restarted
    daemon_reload: yes
    enabled: yes
    name: firewalld


- name: deploy Calico
  become: false
  shell: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
  delegate_to: "{{ item }}"
  run_once: true
  loop:
  - "{{ groups.master[0] }}"


- name: wait node-ready
  import_role:
    name: cni/wait
    # name: configure_nodes/wait_node_ready 
