---
- hosts: master[0]
  gather_facts: false
  become: true
  roles:
    - configure_nodes/create_token

- hosts: worker
  gather_facts: false
  become: true
  roles:
    - configure_nodes/add_worker

- hosts: master[0]
  gather_facts: false
  become: false
  vars:
    wait_target_nodes: "{{groups.worker}}"
  roles:
    - configure_nodes/wait_node_ready
    - configure_nodes/delete_token
