---
- hosts: master[0]
  gather_facts: false
  become: true
  tasks:

    - name: check exists token
      shell: kubeadm token list
      check_mode: false
      changed_when: false
      register: token_exists

    - name: create token
      shell: kubeadm token create --print-join-command
      when: token_exists.stdout == ''
      register: create_token_result

    - debug:
        msg: "{{create_token_result}}"
