---
- hosts: all
  gather_facts: false
  become: true
  roles:
  - role: cni/flannel
    when: use_cni_plugin == 'flannel'

- hosts: all
  gather_facts: false
  become: true
  roles:
  - role: cni/calico
    when: use_cni_plugin == 'calico'

# - hosts: master[0]
#   gather_facts: false
#   roles:
#   - cni/wait
