---
# - hosts: all
#   gather_facts: false
#   become: true
#   roles:
#   - cni/firewall

- hosts: all
  gather_facts: false
  become: true
  roles:
  - cni/calico

- hosts: master[0]
  gather_facts: false
  roles:
  # - cni/flannel
  - cni/wait
