---
- hosts: localhost, master[0]
  roles:
  - configure_ssh/create_key_pair

- hosts: master[0]
  roles:
  - configure_ssh/get_node_pubkey
    # 鍵ファイルのコピー先はハードコーディングしてある

- hosts: all #, !master[0]
  vars:
    public_keys:
    - "{{ lookup('env', 'HOME') + '/.ssh/id_rsa.pub' }}"
    - "/var/tmp/pubkey"
  roles:
  - configure_ssh/add_authorized_key
